#!/usr/bin/env bash
# This script will display numbers from 1 to 10 20 
# and display 4 and then bad luck from china for the 4th iteration
# display 9 and then bad luck from japan for the 9the iteration
# display 17 and then bad luck form italy for the 17 iteration

VAR=1

while [ $VAR -lt 21 ]
do
	case $VAR in
	4)
	echo $VAR
	echo "bad luck from China";;
	9)
	echo $VAR
	echo "bad luck from Japan";;
	17)
	echo $VAR
	echo "bad luck from Italy";;
	*)
	echo $VAR;;
	esac

	((VAR++))
done
