#!/usr/bin/env bash
# This script fives information about the school file

if  [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then 
		echo "school file is not emtpy"
	else
		echo "school file is emtpy"
	fi

	if [ -f "school" ]
	then 
		echo "school is a regular file"
	fi
else
	echo "school file does not exit"
fi
